### ISSUE TITLE
Request to add typical to list of Dynamic checkers

### ISSUE THREAD

**Issue by seandstewart** [ethanhs/python-typecheckers#2]
Hello - I came across this list and I'd like to request that my library be added to the list of Dynamic/Runtime type checkers.

https://github.com/seandstewart/typical

It's currently available on PyPI as well: https://pypi.org/project/typical/

Thanks for putting this together!

**Comment by ethanhs** [comment]
PRs welcome :)

**Comment by seandstewart** [comment]
Hey @ethanhs, I've finally taken the time to do this! PR #3
